// Mocks generated by Mockito 5.0.10 from annotations
// in getxandhasura/test/mocks.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:getxandhasura/features/members/domain/entities/member.dart'
    as _i5;
import 'package:getxandhasura/features/members/domain/repositories/member_repository.dart'
    as _i3;
import 'package:getxandhasura/features/members/domain/usecases/members/get_member_by_id.dart'
    as _i7;
import 'package:getxandhasura/features/members/domain/usecases/members/get_members.dart'
    as _i6;
import 'package:getxandhasura/shared/result.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeResult<T> extends _i1.Fake implements _i2.Result<T> {}

/// A class which mocks [MemberRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemberRepository extends _i1.Mock implements _i3.MemberRepository {
  MockMemberRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<List<_i5.Member>>> getMembers() =>
      (super.noSuchMethod(Invocation.method(#getMembers, []),
              returnValue: Future<_i2.Result<List<_i5.Member>>>.value(
                  _FakeResult<List<_i5.Member>>()))
          as _i4.Future<_i2.Result<List<_i5.Member>>>);
  @override
  _i4.Future<_i2.Result<_i5.Member>> getMemberById(String? id) =>
      (super.noSuchMethod(Invocation.method(#getMemberById, [id]),
              returnValue: Future<_i2.Result<_i5.Member>>.value(
                  _FakeResult<_i5.Member>()))
          as _i4.Future<_i2.Result<_i5.Member>>);
}

/// A class which mocks [GetMembers].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMembers extends _i1.Mock implements _i6.GetMembers {
  MockGetMembers() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<List<_i5.Member>>> call() =>
      (super.noSuchMethod(Invocation.method(#call, []),
              returnValue: Future<_i2.Result<List<_i5.Member>>>.value(
                  _FakeResult<List<_i5.Member>>()))
          as _i4.Future<_i2.Result<List<_i5.Member>>>);
}

/// A class which mocks [GetMemberById].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMemberById extends _i1.Mock implements _i7.GetMemberById {
  MockGetMemberById() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<_i5.Member>> call(String? id) => (super.noSuchMethod(
          Invocation.method(#call, [id]),
          returnValue:
              Future<_i2.Result<_i5.Member>>.value(_FakeResult<_i5.Member>()))
      as _i4.Future<_i2.Result<_i5.Member>>);
}
