name: getxandhasura
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  equatable: ^2.0.2
  hasura_connect: ^3.0.4
  flutter_screenutil: ^5.0.0+2
  connectivity_plus: ^1.0.2
  get:
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^5.0.10
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  fonts:
    - family: Exo
      fonts:
        - asset: assets/fonts/Exo/Exo-Light.ttf
          weight: 300
        - asset: assets/fonts/Exo/Exo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Exo/Exo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Exo/Exo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Exo/Exo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Exo/Exo-Bold.ttf
          weight: 800
        - asset: assets/fonts/Exo/Exo-Bold.ttf
          weight: 900